name: credit_debit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  intl: ^0.19.0
  go_router: ^14.2.7
  pdf: ^3.11.1
  open_file: ^3.2.1
  flutter_pdfview: ^1.3.3
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  device_info_plus: ^10.1.2
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
#  assets:
#    - assets/splash.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_native_splash:
  color: "#40C4FFFF"  # Background color of the splash screen
  image: lib/assets/splash.png  # Path to your splash image (optional)
  fullscreen: true  # Optional: Set to true for fullscreen
